version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backapp
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  frontend: 
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontapp