spring:
  #*****
  #h2
  #*****
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
  #*****
  #jpa
  #*****
  jpa:
#    defer-datasource-initialization: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
#    database-platform: org.hibernate.dialect.H2Dialect
  #*****
  #datasource
  #*****
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
#    driverClassName: org.h2.Driver

  #*****
  #sql for populate database different than h2
  #*****
#  sql:
#    init:
#      mode: always


# Actuators
management:
  endpoint:
    loggers:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, loggers


logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: DEBUG

server:
  error:
    include-message: always